"""Update image model for processing operations

Revision ID: aec15d988238
Revises: aa5c5a0c80aa
Create Date: 2025-05-06 14:45:19.915454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aec15d988238'
down_revision = 'aa5c5a0c80aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('red_pixels', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('green_pixels', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('blue_pixels', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('processed_image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('reception_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('uploader')
        batch_op.drop_column('image_url')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('uploader', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('reception_date')
        batch_op.drop_column('processed_image_url')
        batch_op.drop_column('original_image_url')
        batch_op.drop_column('blue_pixels')
        batch_op.drop_column('green_pixels')
        batch_op.drop_column('red_pixels')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
